apiVersion: v1
kind: ConfigMap
metadata:
  name: __APP_NAME__-config
  namespace: __NAMESPACE__
data:
  AUTH_DISABLED: "false"
  TENANT_ID: "3a680226-db04-4df3-95bd-37b631e11597"
  API_AUDIENCE: "api://d9785590-322c-48e6-ba58-a00aabb5aee5"
  CORS_ALLOWED_ORIGINS: "https://__HOST__"
