apiVersion: v1
kind: ConfigMap
metadata:
  name: __APP_NAME__-config
  namespace: __NAMESPACE__
data:
  AUTH_DISABLED: "false"
  TENANT_ID: "__TENANT_ID__"
  API_AUDIENCE: "__API_AUDIENCE__"
  CORS_ALLOWED_ORIGINS: "https://__HOST__"
  VITE_CLIENT_ID: "__SPA_CLIENT_ID__"
  VITE_TENANT_ID: "__TENANT_ID__"
  VITE_API_SCOPE: "__API_SCOPE__"
