apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glossary
  namespace: glossary-production
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: glossary.graphras.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glossary
                port:
                  number: 80
  tls:
    - hosts:
        - glossary.graphras.com
      secretName: glossary-graphras-com-tls
